version: '3.8'

services:
  db:
    image: postgres:16
    container_name: langgraph_pg
    environment:
      POSTGRES_USER: langgraph
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: claims_db  # This ensures the DB is created if it doesn't exist
#      POSTGRES_DB: langgraph_memory  # This ensures the DB is created if it doesn't exist
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

volumes:
  pgdata:
